<?php

namespace AppBundle\Entity;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use Doctrine\ORM\AbstractQuery;
use Doctrine\ORM\EntityRepository;

class StudentRepository extends EntityRepository
{
    public function findStudents($id = null)
    {
        $qb = $this
            ->createQueryBuilder('s')
        ;

        if( null !== $id){
            $qb
                ->where('s.id = :id')
                ->setParameter(':id', $id)
            ;
        }
        return  null === $id ? $qb->getQuery()->getArrayResult() : $qb->getQuery()->getSingleResult(AbstractQuery::HYDRATE_ARRAY);

    }
}
